### ISSUE TITLE
Integration into mlc-llm workflow

### ISSUE THREAD

**Issue by ylc2001** [tlc-pack/libflash_attn#1]
Do you know how we can integrate flash attn v2 into [mlc-llm](https://github.com/mlc-ai/mlc-llm)?

I'm currently working on optimizing inference performance based on mlc-llm and am considering replacing the primfuncs for attention with flash attn v2. Any possible ideas for implementation?

**Comment by masahi** [comment]
I'm going to integrate flash v2 into TVM CUTLASS BYOC, which can be used for offloading Relax `attention` op to flash or xformer attention kernel. However, flash v2 cannot be used for decoding since its notion of causal masking is different from what we need. See https://github.com/Dao-AILab/flash-attention/issues/282
